# modules/report_generator.py (v4.5 - FPDF2 FIXED)
from fpdf import FPDF
import datetime

class PDFReport(FPDF):
    def header(self):
        self.set_font('Helvetica', 'B', 15)
        self.cell(0, 10, 'ValuePy - Forensic Analysis Report', ln=True, align='C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', align='C')

def clean_text(text):
    """
    Αφαιρεί emojis και σύμβολα που δεν υποστηρίζει η Helvetica.
    """
    if text is None:
        return ""
    text = str(text)
    
    # Λίστα με χαρακτήρες προς αφαίρεση/αντικατάσταση
    replacements = {
        "🟢": "", 
        "🔴": "", 
        "⚠️": "", 
        "🚩": "", 
        "✅": "",
        "€": "EUR " 
    }
    
    for char, replacement in replacements.items():
        text = text.replace(char, replacement)
    
    return text.strip()

def create_pdf_bytes(company_name, forensics_data):
    pdf = PDFReport()
    pdf.add_page()
    
    # 1. Title & Date
    pdf.set_font("Helvetica", "B", 20)
    pdf.cell(0, 15, txt=f"Report: {clean_text(company_name)}", ln=True, align='L')
    
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 10, txt=f"Generated on: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}", ln=True)
    pdf.line(10, 35, 200, 35)
    pdf.ln(10)

    # Shortcuts
    p1 = forensics_data.get('Pillar_1', {})
    p2 = forensics_data.get('Pillar_2', {})
    p3 = forensics_data.get('Pillar_3', {})
    p4 = forensics_data.get('Pillar_4', {})
    p5 = forensics_data.get('Pillar_5', {})

    # 2. Executive Summary (The 5 Pillars)
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "I. Executive Summary (The 5 Pillars)", ln=True)
    pdf.ln(2)

    # Function for rows
    def add_metric(label, value, flag=None):
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(50, 8, label, border=0)
        pdf.set_font("Helvetica", "", 11)
        
        # ΚΑΘΑΡΙΣΜΟΣ ΤΙΜΗΣ ΑΠΟ EMOJIS
        clean_val = clean_text(value)
        text = str(clean_val)
        
        # Χειρισμός Flag (Warning Text)
        if flag and isinstance(flag, str):
            if "RED" in flag or "ZOMBIE" in flag or "DESTROYING" in flag:
                text += "  [WARNING]"
        
        pdf.cell(0, 8, text, ln=True)

    # P1
    add_metric("Earnings Quality:", p1.get('Flag', '-'), p1.get('Flag'))
    add_metric("Gap (Net - CFO):", f"{p1.get('Gap', 0)/1000000:.1f} M")
    
    # P2
    pdf.ln(2)
    add_metric("Solvency:", p2.get('Flag_Solvency', '-'), p2.get('Flag_Solvency'))
    add_metric("DSO (Days):", f"{p2.get('DSO', 0):.0f}")
    
    # P3
    pdf.ln(2)
    add_metric("ROE (Return):", f"{p3.get('ROE', 0)}%")
    add_metric("Profit Margin:", f"{p3.get('Net_Margin', 0)}%")
    
    # P4
    pdf.ln(2)
    growth_status = "Overtrading" if p4.get('Overtrading') else "Sustainable"
    add_metric("Growth Status:", growth_status)
    add_metric("Actual Growth:", f"{p4.get('Actual_Growth', 0)}%")
    
    # P5
    pdf.ln(2)
    add_metric("Value Creation:", p5.get('Value_Creation', '-'))
    add_metric("EVA (Econ. Value):", f"{p5.get('EVA', 0)} M")

    pdf.ln(10)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(5)

    # 3. Disclaimer
    pdf.set_font("Helvetica", "I", 8)
    pdf.multi_cell(0, 5, "Disclaimer: This report is generated by ValuePy AI algorithms for educational purposes only. It does not constitute financial advice.")

    # === Η ΑΛΛΑΓΗ ΕΙΝΑΙ ΕΔΩ (ΓΡΑΜΜΗ 116) ===
    # Επιστρέφουμε τα bytes απευθείας. Χωρίς encode.
    return bytes(pdf.output())